export const hostedCapabilityEnvironmentNames = [
  "KINRESOLVE_DNA_ENABLED",
  "KINRESOLVE_EXTERNAL_AI_ENABLED",
  "KINRESOLVE_PUBLIC_ARCHIVE_ENABLED",
  "KINRESOLVE_PUBLIC_PUBLISHING_ENABLED",
  "KINRESOLVE_EVIDENCE_BINARY_UPLOADS_ENABLED",
  "KINRESOLVE_PACKAGE_MEDIA_ENABLED",
  "KINRESOLVE_PLAIN_GEDCOM_ENABLED"
] as const;
